### ISSUE TITLE
Improve reverse proxy

### ISSUE THREAD

**Issue by kawa-marcin** [optimor/reverse-proxy#19]
- [ ] Fix `next` logic after session expires
  - This task can not be accomplished. The problem relates to the URL hash (`#`) that is not sent to the server hence it's impossible to redirect correctly.
- [ ] Write tests
- [x] Use black for code formatting
- [x] Lint and run black

**Comment by jstockwin** [comment]
We do not have the bandwidth to get around to this issue, closing
